# -*- coding: utf-8 -*-
"""난임 프로젝트 EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JooDDn2Pkm3lQj2dkqerz7lm0Apdrsys
"""

# pip install koreanize-matplotlib

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

import matplotlib
import koreanize_matplotlib  # import만 해도 자동 적용!

# 한글 폰트 설정
import subprocess
subprocess.run(['apt-get', 'install', '-y', 'fonts-nanum'], capture_output=True)

fm._load_fontmanager(try_read_cache=False)

# 설치된 한글 폰트 목록 확인
korean_fonts = [f for f in fm.findSystemFonts() if any(k in f for k in ['nanum', 'Nanum', 'gothic', 'Gothic', 'korean', 'Korean'])]
print(korean_fonts)

font_path = korean_fonts[0]  # 또는 출력된 경로 직접 입력

fm.fontManager.addfont(font_path)
matplotlib.rc('font', family='NanumGothic')
matplotlib.rcParams['axes.unicode_minus'] = False

# ── 데이터 로드 ─────────────────────────────────────────────────────────────
# df = pd.read_csv("/Users/admin/Desktop/infertility/open (1)/train.csv")
df = pd.read_csv("/content/drive/MyDrive/헬스케어 3기/프로젝트/미니프로젝트3/open (1)/train.csv")


print("=" * 60)
print("📊 데이터 기본 정보")
print("=" * 60)
print(f"행 수     : {df.shape[0]:,}")
print(f"열 수     : {df.shape[1]}")
print(f"중복 행   : {df.duplicated().sum()}")
print()


# ── 1. 타겟 분포 ─────────────────────────────────────────────────────────────
print("=" * 60)
print("🎯 1. 타겟 변수 분포 (임신 성공 여부)")
print("=" * 60)
target_counts = df['임신 성공 여부'].value_counts()
target_ratio  = df['임신 성공 여부'].value_counts(normalize=True) * 100
print(target_counts)
print(f"\n성공 비율: {target_ratio[1]:.2f}% | 실패 비율: {target_ratio[0]:.2f}%")
print(f"클래스 불균형 비율: 1 : {target_ratio[0]/target_ratio[1]:.1f}")

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle('타겟 변수 분포 (임신 성공 여부)', fontsize=14, fontweight='bold')

axes[0].bar(['실패(0)', '성공(1)'], target_counts.values, color=['#EF5350', '#42A5F5'])
axes[0].set_title('클래스별 샘플 수')
for i, v in enumerate(target_counts.values):
    axes[0].text(i, v + 1000, f'{v:,}', ha='center', fontweight='bold')

axes[1].pie(target_counts.values, labels=['실패(0)', '성공(1)'],
            autopct='%1.1f%%', colors=['#EF5350', '#42A5F5'], startangle=90)
axes[1].set_title('클래스 비율')

plt.tight_layout()
plt.savefig('eda_01_target_distribution.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ 저장: eda_01_target_distribution.png\n")


# ── 2. 결측치 분석 ─────────────────────────────────────────────────────────────
print("=" * 60)
print("🔍 2. 결측치 분석")
print("=" * 60)
missing = df.isnull().sum()
missing_ratio = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({'결측 수': missing, '결측률(%)': missing_ratio})
missing_df = missing_df[missing_df['결측 수'] > 0].sort_values('결측률(%)', ascending=False)
print(missing_df.to_string())
print(f"\n결측치 있는 컬럼 수: {len(missing_df)} / {df.shape[1]}")

if len(missing_df) > 0:
    fig, ax = plt.subplots(figsize=(10, max(5, len(missing_df) * 0.4)))
    colors = ['#EF5350' if r > 50 else '#FFA726' if r > 20 else '#66BB6A'
                for r in missing_df['결측률(%)']]
    bars = ax.barh(missing_df.index, missing_df['결측률(%)'], color=colors)
    ax.set_xlabel('결측률 (%)')
    ax.set_title('컬럼별 결측률', fontsize=13, fontweight='bold')
    ax.axvline(x=50, color='red', linestyle='--', alpha=0.5, label='50% 기준선')
    ax.axvline(x=20, color='orange', linestyle='--', alpha=0.5, label='20% 기준선')
    ax.legend()
    for bar, val in zip(bars, missing_df['결측률(%)']):
        ax.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height()/2,
                f'{val:.1f}%', va='center', fontsize=8)
    plt.tight_layout()
    plt.savefig('eda_02_missing_values.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("✅ 저장: eda_02_missing_values.png\n")


# ── 3. 수치형 변수 분포 ──────────────────────────────────────────────────────
print("=" * 60)
print("📈 3. 수치형 변수 기초 통계")
print("=" * 60)
num_cols = df.select_dtypes(include='number').columns.tolist()
num_cols = [c for c in num_cols if c != '임신 성공 여부']

print(df[num_cols].describe().T.round(2).to_string())

# 수치형 변수 히스토그램 (상위 12개)
plot_cols = num_cols[:12]
fig, axes = plt.subplots(3, 4, figsize=(18, 12))
fig.suptitle('수치형 변수 분포', fontsize=14, fontweight='bold')
axes = axes.flatten()

for i, col in enumerate(plot_cols):
    data = df[col].dropna()
    axes[i].hist(data, bins=30, color='#42A5F5', alpha=0.7, edgecolor='white')
    axes[i].set_title(col, fontsize=9)
    axes[i].set_xlabel('')
    axes[i].tick_params(labelsize=7)

for j in range(len(plot_cols), len(axes)):
    axes[j].set_visible(False)

plt.tight_layout()
plt.savefig('eda_03_numeric_distribution.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ 저장: eda_03_numeric_distribution.png\n")


# ── 4. 범주형 변수 분포 ──────────────────────────────────────────────────────
print("=" * 60)
print("📊 4. 범주형 변수 분포")
print("=" * 60)
cat_cols = df.select_dtypes(include='object').columns.tolist()
cat_cols = [c for c in cat_cols if c not in ['ID', '시술 시기 코드']]

for col in cat_cols:
    vc = df[col].value_counts()
    print(f"\n[{col}] (고유값: {df[col].nunique()}개)")
    print(vc.head(10).to_string())

# 주요 범주형 변수 시각화
plot_cat_cols = [c for c in cat_cols if df[c].nunique() <= 15][:6]
if plot_cat_cols:
    fig, axes = plt.subplots(2, 3, figsize=(18, 10))
    fig.suptitle('주요 범주형 변수 분포', fontsize=14, fontweight='bold')
    axes = axes.flatten()

    for i, col in enumerate(plot_cat_cols):
        vc = df[col].value_counts()
        axes[i].bar(range(len(vc)), vc.values, color=plt.cm.Set2(np.linspace(0, 1, len(vc))))
        axes[i].set_xticks(range(len(vc)))
        axes[i].set_xticklabels(vc.index, rotation=30, ha='right', fontsize=8)
        axes[i].set_title(col, fontsize=10)

    for j in range(len(plot_cat_cols), len(axes)):
        axes[j].set_visible(False)

    plt.tight_layout()
    plt.savefig('eda_04_categorical_distribution.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("✅ 저장: eda_04_categorical_distribution.png\n")


# ── 5. 타겟 vs 주요 변수 관계 ────────────────────────────────────────────────
print("=" * 60)
print("🎯 5. 타겟과 주요 변수 관계 분석")
print("=" * 60)

# 5-1. 나이별 임신 성공률
print("\n[시술 당시 나이별 성공률]")
age_success = df.groupby('시술 당시 나이')['임신 성공 여부'].mean().sort_values(ascending=False)
print(age_success.round(3).to_string())

fig, axes = plt.subplots(1, 2, figsize=(14, 6))
fig.suptitle('타겟과 주요 변수 관계', fontsize=13, fontweight='bold')

age_order = ['만18-34세', '만35-37세', '만38-39세', '만40-42세', '만43-44세', '만45-50세']
age_success_ordered = df.groupby('시술 당시 나이')['임신 성공 여부'].mean()
age_success_ordered = age_success_ordered.reindex([a for a in age_order if a in age_success_ordered.index])

axes[0].bar(range(len(age_success_ordered)), age_success_ordered.values * 100,
            color=plt.cm.RdYlGn(np.linspace(0.7, 0.1, len(age_success_ordered))))
axes[0].set_xticks(range(len(age_success_ordered)))
axes[0].set_xticklabels(age_success_ordered.index, rotation=20, ha='right', fontsize=9)
axes[0].set_ylabel('임신 성공률 (%)')
axes[0].set_title('나이별 임신 성공률')

# 5-2. 시술 유형별 임신 성공률
type_success = df.groupby('시술 유형')['임신 성공 여부'].mean().sort_values(ascending=False)
axes[1].barh(range(len(type_success)), type_success.values * 100, color='#42A5F5')
axes[1].set_yticks(range(len(type_success)))
axes[1].set_yticklabels(type_success.index, fontsize=9)
axes[1].set_xlabel('임신 성공률 (%)')
axes[1].set_title('시술 유형별 임신 성공률')

plt.tight_layout()
plt.savefig('eda_05_target_vs_features.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ 저장: eda_05_target_vs_features.png\n")


# ── 6. 수치형 변수 - 타겟 상관관계 ────────────────────────────────────────────
print("=" * 60)
print("📉 6. 수치형 변수와 타겟 상관관계")
print("=" * 60)
num_df = df[num_cols + ['임신 성공 여부']].copy()
corr_target = num_df.corr()['임신 성공 여부'].drop('임신 성공 여부').sort_values(key=abs, ascending=False)
print(corr_target.round(4).to_string())

# 상관관계 히트맵 (상위 상관 변수)
top_corr_cols = corr_target.head(15).index.tolist()
corr_matrix = num_df[top_corr_cols + ['임신 성공 여부']].corr()

fig, axes = plt.subplots(1, 2, figsize=(18, 6))
fig.suptitle('수치형 변수 상관관계', fontsize=13, fontweight='bold')

# 타겟 상관관계 bar
colors = ['#EF5350' if v < 0 else '#42A5F5' for v in corr_target.head(15).values]
axes[0].barh(range(len(corr_target.head(15))), corr_target.head(15).values, color=colors)
axes[0].set_yticks(range(len(corr_target.head(15))))
axes[0].set_yticklabels(corr_target.head(15).index, fontsize=8)
axes[0].set_xlabel('Pearson 상관계수')
axes[0].set_title('타겟과 수치형 변수 상관관계 (상위 15개)')
axes[0].axvline(0, color='black', linewidth=0.8)

# 히트맵
sns.heatmap(corr_matrix, annot=False, cmap='coolwarm', center=0,
            ax=axes[1], linewidths=0.5, cbar_kws={'shrink': 0.8})
axes[1].set_title('상관관계 히트맵 (상위 15개 + 타겟)')
axes[1].tick_params(axis='x', rotation=45, labelsize=7)
axes[1].tick_params(axis='y', rotation=0, labelsize=7)

plt.tight_layout()
plt.savefig('eda_06_correlation.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ 저장: eda_06_correlation.png\n")


# ── 7. 배아 관련 핵심 수치 분석 ──────────────────────────────────────────────
print("=" * 60)
print("🔬 7. 배아 관련 변수 분석")
print("=" * 60)
embryo_cols = ['총 생성 배아 수', '이식된 배아 수', '저장된 배아 수',
                '미세주입된 난자 수', '수집된 신선 난자 수']
embryo_cols_exist = [c for c in embryo_cols if c in df.columns]

fig, axes = plt.subplots(1, len(embryo_cols_exist), figsize=(18, 5))
fig.suptitle('배아 관련 변수 - 임신 성공/실패 비교 (boxplot)', fontsize=13, fontweight='bold')

for i, col in enumerate(embryo_cols_exist):
    success  = df[df['임신 성공 여부'] == 1][col].dropna()
    fail     = df[df['임신 성공 여부'] == 0][col].dropna()
    axes[i].boxplot([fail, success], labels=['실패(0)', '성공(1)'],
                    patch_artist=True,
                    boxprops=dict(facecolor='#EF535050', color='#EF5350'),
                    medianprops=dict(color='black', linewidth=2))
    axes[i].set_title(col, fontsize=9)
    axes[i].set_ylabel('값')

plt.tight_layout()
plt.savefig('eda_07_embryo_analysis.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ 저장: eda_07_embryo_analysis.png\n")


# ── 최종 요약 ────────────────────────────────────────────────────────────────
print("=" * 60)
print("📋 EDA 요약")
print("=" * 60)
print(f"총 샘플 수         : {len(df):,}")
print(f"피처 수            : {df.shape[1] - 2} (ID·타겟 제외)")
print(f"수치형 변수        : {len(num_cols)}개")
print(f"범주형 변수        : {len(cat_cols)}개")
print(f"결측치 있는 컬럼   : {len(missing_df)}개")
print(f"타겟 클래스 비율   : 성공 {target_ratio[1]:.1f}% / 실패 {target_ratio[0]:.1f}%")
print(f"타겟 상관 최고 변수: {corr_target.index[0]} ({corr_target.iloc[0]:.4f})")
print()
print("생성된 파일:")
for i in range(1, 8):
    print(f"  eda_0{i}_*.png")

# ══════════════════════════════════════════════════════════════
# 추가 EDA 1. 불임 원인 조합 분석
# ══════════════════════════════════════════════════════════════
print("=" * 60)
print("🧬 추가 EDA 1. 불임 원인 조합 분석")
print("=" * 60)

infertility_cols = [
    '불임 원인 - 난관 질환', '불임 원인 - 남성 요인', '불임 원인 - 배란 장애',
    '불임 원인 - 여성 요인', '불임 원인 - 자궁경부 문제', '불임 원인 - 자궁내막증',
    '불임 원인 - 정자 농도', '불임 원인 - 정자 면역학적 요인',
    '불임 원인 - 정자 운동성', '불임 원인 - 정자 형태',
    '불명확 불임 원인',
    '남성 주 불임 원인', '남성 부 불임 원인',
    '여성 주 불임 원인', '여성 부 불임 원인',
]
infertility_cols = [c for c in infertility_cols if c in df.columns]

# 1-1. 원인별 성공률 비교
inf_success = {}
for col in infertility_cols:
    group = df[df[col] == 1]
    if len(group) > 100:
        inf_success[col] = {
            '성공률': group['임신 성공 여부'].mean() * 100,
            '샘플 수': len(group)
        }

inf_df = pd.DataFrame(inf_success).T.sort_values('성공률', ascending=True)
overall_rate = df['임신 성공 여부'].mean() * 100
print(f"\n전체 평균 성공률: {overall_rate:.2f}%")
print(inf_df.round(2).to_string())

# 1-2. 불임 원인 개수 분포
specific_causes = [c for c in infertility_cols if '불임 원인 -' in c]
df['불임_원인_개수'] = df[specific_causes].sum(axis=1)
cause_count_success = df.groupby('불임_원인_개수')['임신 성공 여부'].agg(['mean', 'count'])
cause_count_success.columns = ['성공률', '샘플 수']
cause_count_success['성공률'] *= 100
print(f"\n[불임 원인 개수별 성공률]")
print(cause_count_success.round(2).to_string())

fig, axes = plt.subplots(1, 2, figsize=(16, 7))
fig.suptitle('불임 원인 조합 분석', fontsize=14, fontweight='bold')

# 원인별 성공률 bar
colors = ['#EF5350' if v < overall_rate else '#42A5F5' for v in inf_df['성공률']]
bars = axes[0].barh(range(len(inf_df)), inf_df['성공률'], color=colors)
axes[0].set_yticks(range(len(inf_df)))
axes[0].set_yticklabels(inf_df.index, fontsize=8)
axes[0].axvline(overall_rate, color='black', linestyle='--', linewidth=1.2, label=f'전체 평균 {overall_rate:.1f}%')
axes[0].set_xlabel('임신 성공률 (%)')
axes[0].set_title('불임 원인별 임신 성공률\n(파랑=평균 이상, 빨강=평균 이하)')
axes[0].legend(fontsize=9)
for bar, val in zip(bars, inf_df['성공률']):
    axes[0].text(bar.get_width() + 0.2, bar.get_y() + bar.get_height()/2,
                    f'{val:.1f}%', va='center', fontsize=8)

# 원인 개수별 성공률
valid = cause_count_success[cause_count_success['샘플 수'] >= 100]
axes[1].bar(valid.index.astype(str), valid['성공률'],
            color=plt.cm.RdYlGn(np.linspace(0.8, 0.2, len(valid))))
axes[1].axhline(overall_rate, color='black', linestyle='--', linewidth=1.2, label=f'전체 평균 {overall_rate:.1f}%')
axes[1].set_xlabel('불임 원인 개수')
axes[1].set_ylabel('임신 성공률 (%)')
axes[1].set_title('불임 원인 개수별 임신 성공률')
axes[1].legend(fontsize=9)
for i, (idx, row) in enumerate(valid.iterrows()):
    axes[1].text(i, row['성공률'] + 0.3, f"{row['성공률']:.1f}%", ha='center', fontsize=9)

plt.tight_layout()
plt.savefig('eda_08_infertility_cause.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ 저장: eda_08_infertility_cause.png\n")


# ══════════════════════════════════════════════════════════════
# 추가 EDA 2. 시술 횟수 vs 성공률
# ══════════════════════════════════════════════════════════════
print("=" * 60)
print("🔁 추가 EDA 2. 시술 횟수 vs 임신 성공률")
print("=" * 60)

count_cols = {
    '총 시술 횟수': '전체',
    '클리닉 내 총 시술 횟수': '클리닉 내',
    'IVF 시술 횟수': 'IVF',
    'DI 시술 횟수': 'DI',
}
count_cols = {k: v for k, v in count_cols.items() if k in df.columns}

# 횟수 컬럼 숫자 변환 (범주형으로 저장된 경우 대비)
order_map = {'0회': 0, '1회': 1, '2회': 2, '3회': 3, '4회': 4, '5회': 5, '6회 이상': 6}
for col in count_cols:
    if df[col].dtype == object:
        df[col + '_num'] = df[col].map(order_map)
    else:
        df[col + '_num'] = df[col]

fig, axes = plt.subplots(1, len(count_cols), figsize=(18, 6))
fig.suptitle('시술 횟수별 임신 성공률', fontsize=14, fontweight='bold')
if len(count_cols) == 1:
    axes = [axes]

for i, (col, label) in enumerate(count_cols.items()):
    num_col = col + '_num'
    grp = df.groupby(num_col)['임신 성공 여부'].agg(['mean', 'count']).reset_index()
    grp = grp[grp['count'] >= 100]
    grp['mean'] *= 100

    color_vals = plt.cm.Blues(np.linspace(0.3, 0.9, len(grp)))
    bars = axes[i].bar(grp[num_col].astype(str), grp['mean'], color=color_vals)
    axes[i].axhline(overall_rate, color='red', linestyle='--', linewidth=1, label=f'전체 평균 {overall_rate:.1f}%')
    axes[i].set_xlabel('시술 횟수')
    axes[i].set_ylabel('임신 성공률 (%)')
    axes[i].set_title(f'{label} 시술 횟수별 성공률')
    axes[i].legend(fontsize=8)
    for bar, (_, row) in zip(bars, grp.iterrows()):
        axes[i].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,
                        f"{row['mean']:.1f}%", ha='center', fontsize=8)

    print(f"\n[{label} 시술 횟수별 성공률]")
    print(grp[[num_col, 'mean', 'count']].rename(
        columns={num_col: '횟수', 'mean': '성공률(%)', 'count': '샘플 수'}).to_string(index=False))

plt.tight_layout()
plt.savefig('eda_09_attempt_vs_success.png', dpi=150, bbox_inches='tight')
plt.show()
print("\n✅ 저장: eda_09_attempt_vs_success.png\n")


# ══════════════════════════════════════════════════════════════
# 추가 EDA 3. 경과일 변수 결측 패턴 분석
# ══════════════════════════════════════════════════════════════
print("=" * 60)
print("📅 추가 EDA 3. 경과일 변수 결측 패턴 분석")
print("=" * 60)

date_cols = ['난자 채취 경과일', '난자 해동 경과일', '난자 혼합 경과일', '배아 이식 경과일', '배아 해동 경과일']
date_cols = [c for c in date_cols if c in df.columns]

# 3-1. 시술 유형별 결측률
print("\n[시술 유형별 경과일 결측률 (%)]")
missing_by_type = df.groupby('시술 유형')[date_cols].apply(
    lambda x: x.isnull().mean() * 100).round(1)
print(missing_by_type.to_string())

# 3-2. 결측 패턴 (어떤 조합으로 결측되는지)
df['경과일_결측_패턴'] = df[date_cols].isnull().astype(int).astype(str).apply(''.join, axis=1)
pattern_counts = df['경과일_결측_패턴'].value_counts().head(10)
pattern_success = df.groupby('경과일_결측_패턴')['임신 성공 여부'].mean() * 100

print(f"\n[경과일 결측 패턴 상위 10개] (1=결측, 0=존재, 순서: {date_cols})")
pattern_df = pd.DataFrame({'빈도': pattern_counts, '성공률(%)': pattern_success}).dropna()
pattern_df['성공률(%)'] = pattern_df['성공률(%)'].round(2)
print(pattern_df.to_string())

fig, axes = plt.subplots(1, 2, figsize=(16, 7))
fig.suptitle('경과일 변수 결측 패턴 분석', fontsize=14, fontweight='bold')

# 시술 유형별 결측률 히트맵
sns.heatmap(missing_by_type, annot=True, fmt='.1f', cmap='Reds',
            ax=axes[0], linewidths=0.5, cbar_kws={'label': '결측률 (%)'})
axes[0].set_title('시술 유형별 경과일 결측률 (%)')
axes[0].set_xlabel('경과일 변수')
axes[0].set_ylabel('시술 유형')
axes[0].tick_params(axis='x', rotation=30, labelsize=8)

# 결측 패턴별 성공률
top_patterns = pattern_df.head(8)
bar_colors = ['#42A5F5' if v >= overall_rate else '#EF5350' for v in top_patterns['성공률(%)']]
axes[1].barh(range(len(top_patterns)), top_patterns['성공률(%)'], color=bar_colors)
axes[1].set_yticks(range(len(top_patterns)))
axes[1].set_yticklabels([f"{p}\n(n={int(top_patterns['빈도'].iloc[i]):,})"
                            for i, p in enumerate(top_patterns.index)], fontsize=8)
axes[1].axvline(overall_rate, color='black', linestyle='--', linewidth=1.2,
                label=f'전체 평균 {overall_rate:.1f}%')
axes[1].set_xlabel('임신 성공률 (%)')
axes[1].set_title(f'결측 패턴별 성공률\n(1=결측, 순서: 채취/해동/혼합/이식/배아해동)')
axes[1].legend(fontsize=9)

plt.tight_layout()
plt.savefig('eda_10_missing_pattern.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ 저장: eda_10_missing_pattern.png\n")

print("=" * 60)
print("📋 추가 EDA 완료")
print("=" * 60)
print("생성된 파일:")
print("  eda_08_infertility_cause.png  - 불임 원인 조합 분석")
print("  eda_09_attempt_vs_success.png - 시술 횟수 vs 성공률")
print("  eda_10_missing_pattern.png    - 경과일 결측 패턴 분석")